openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://localhost:8080
paths:
  /hello:
    get:
      description: this is used to get a greeting message from the server
      operationId: sayHello
      parameters:
      - explode: true
        in: query
        name: name
        required: true
        schema:
          type: string
        style: form
      responses:
        "400":
          description: you did something wrong
        "200":
          content:
            '*/*':
              schema:
                type: string
          description: everything is ok when getting the message
      tags:
      - sample-controller
      x-accepts: '*/*'
    post:
      operationId: sayHelloPost
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                type: string
          description: OK
      tags:
      - sample-controller
      x-contentType: application/json
      x-accepts: '*/*'
components:
  schemas: {}

