/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SampleControllerApi
 */
@Ignore
public class SampleControllerApiTest {

    private final SampleControllerApi api = new SampleControllerApi();

    
    /**
     * 
     *
     * this is used to get a greeting message from the server
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sayHelloTest() {
        String name = null;
        String response = api.sayHello(name);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sayHelloPostTest() {
        String body = null;
        String response = api.sayHelloPost(body);

        // TODO: test validations
    }
    
}
