package com.revature.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-26T17:14:02.991-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ws.revature.com/", name = "ItemRestock")
@XmlSeeAlso({ObjectFactory.class})
public interface ItemRestock {

    @WebMethod
    @RequestWrapper(localName = "restockItem", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.RestockItem")
    @ResponseWrapper(localName = "restockItemResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.RestockItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String restockItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Item arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "discontinueItem", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DiscontinueItem")
    @ResponseWrapper(localName = "discontinueItemResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DiscontinueItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String discontinueItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Item arg0
    );

    @WebMethod
    @RequestWrapper(localName = "canRestock", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.CanRestock")
    @ResponseWrapper(localName = "canRestockResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.CanRestockResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean canRestock(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Item arg0
    );
}
