package com.revature.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-01T17:06:29.332-04:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "ItemRestockImplService",
                  wsdlLocation = "http://localhost:8080/SOAPService/restock?wsdl",
                  targetNamespace = "http://ws.revature.com/")
public class ItemRestockImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.revature.com/", "ItemRestockImplService");
    public final static QName ItemRestockImplPort = new QName("http://ws.revature.com/", "ItemRestockImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAPService/restock?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ItemRestockImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAPService/restock?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ItemRestockImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ItemRestockImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemRestockImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ItemRestockImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ItemRestockImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ItemRestockImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ItemRestock
     */
    @WebEndpoint(name = "ItemRestockImplPort")
    public ItemRestock getItemRestockImplPort() {
        return super.getPort(ItemRestockImplPort, ItemRestock.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemRestock
     */
    @WebEndpoint(name = "ItemRestockImplPort")
    public ItemRestock getItemRestockImplPort(WebServiceFeature... features) {
        return super.getPort(ItemRestockImplPort, ItemRestock.class, features);
    }

}
